@startuml
Class IVMApplication{
}

Class InventoryItem{
+ String description
+ String serial
+ String price

+ getDescription()
+ getSerial()
+ getPrice()

+ setDescription()
+ setSerial()
+ setPrice()
}

Class InventoryGUI{

}

Class IVMController{
 + addItemToList()
 + addNewItemFromField()
 + addSerialNumberFromField()
 + addPriceFromField()
 + clearItemFromList()
 + deleteItemFromList()
 + searchFilteredList()
 +initialize()
 +initTable()
 +initCol()
 +editCols()

}

Class InputValidator{
  + validItem()
  + validInput()
  + validSerial()
}

IVMApplication --> InventoryItem

InventoryGUI --> InventoryItem
@enduml